---

- hosts: localhost
  connection: local
  become: false
  vars:
    group_role: cluster-admin
    GITHUB_ORGANIZATION: open-cluster-management
    GITHUB_TOKEN: "{{ lookup('env', 'GITHUB_TOKEN') | default('', True) }}"
    home: "{{ lookup('env', 'HOME') | default('', True) }}"
    organization_groups:
    - SRE
    optional_vars_file: "{{ home }}/external_vars.yml"
  tasks:

  - include_vars: "{{ optional_vars_file }}"
    when: optional_vars_file is file

  - name: Ensure that mch-imageRepository is set
    shell: |
      oc get pods -o yaml | grep "image:" | sort -u | grep -v f:image | sed s'#    -#     #' | sort -u | grep "quay.io"
    register: output

  - name: Verify the number of quay.io:443 images is enough
    debug:
      msg: 
      - "{{ output.stdout_lines }}"

  - name: check quay count
    shell: |
      exit 1
    when: output.stdout_lines | list | count < 31

  - name: Successful validation
    debug:
      msg: 
      - "{{ output.stdout_lines }}"
